### ISSUE TITLE
About the feeds

### ISSUE THREAD

**Issue by L0rdGRiM-0** [bhigginsuk/discord-rss-fetcher#19]
Where can I edit the preview of the posts?

**Comment by benji7425** [comment]
If you are using a manual deployment on your own server you can modify [src/core/article-poster.ts](https://github.com/benji7425/discord-rss-fetcher/blob/master/src/core/article-poster.ts) to change this behaviour. The currently used format is generated using the [html-to-text](https://www.npmjs.com/package/html-to-text) package, on [L38](https://github.com/benji7425/discord-rss-fetcher/blob/master/src/core/article-poster.ts#L38).
