### ISSUE TITLE
Bot's Help Links Expired

### ISSUE THREAD

**Issue by Tonkatunk** [bhigginsuk/discord-rss-fetcher#20]
The RSS Fetcher, when you do @RSS_Fetcher help, will link to a github and discord at the bottom of its post.  The current links both go to dead pages.

Expired Github link: https://benji7425.github.io/
Expected Github link (possibly): https://github.com/benjihiggins/discord-rss-fetcher or https://benji7425.io/ (remove the .github)

Expired Discord link: https://discord.gg/SSkbwSJ
Expected Discord link: ?

**Comment by bhigginsuk** [comment]
Hey, sorry for the late reply, I somehow missed the notification for this issue way back when and only just saw it today.

Thanks for raising this, I had actually completely forgot about these messages. It's a little bit of a pain to update them as I was somewhat lazy and just [hard-coded them in my bot framework](https://github.com/bhigginsuk/disharmony/blob/master/src/inbuilt-commands/help.ts), so updating them will require me to publish new bot versions!

I'll put it on my todo list, thanks for pointing it out.

**Comment by bhigginsuk** [comment]
This should be fixed as of [v4.1.3](https://github.com/bhigginsuk/discord-rss-fetcher/releases/tag/v4.1.3).
