### ISSUE TITLE
Bot docker install fail on last version.

### ISSUE THREAD

**Issue by dvir001** [bhigginsuk/discord-rss-fetcher#24]
The docker wont create a DB file and will fail to complete setup on new version, older docker version 4.1.0 is working fine.

**Comment by benjihiggins** [comment]
Thanks for raising this, I was able to replicate. Should be fixed in v4.1.2, which is now pushed as latest :+1:

**Comment by bhigginsuk** [comment]
Closing this as I believe the issue to be fixed. Please reopen if you are still having issues.
