### ISSUE TITLE
Bot is online but does not Respond to any commands

### ISSUE THREAD

**Issue by jzvi12** [bhigginsuk/discord-rss-fetcher#25]
Could you please shed some light?
![image](https://user-images.githubusercontent.com/10729787/113947049-cdb6bc80-97d7-11eb-9eaf-5a7e128ea565.png)

**Comment by bhigginsuk** [comment]
You need to @mention the bot by the actual name or nickname you've given it, just like you would do with another user account if you wanted to ping them. In the examples I give, the bot was named 'RSS Fetcher'. When you've mentioned it correctly it's name should be purple and clickable, like with any other user.

**Comment by bhigginsuk** [comment]
Feel free to reopen this if you're still having issues
