### ISSUE TITLE
Bot is closing due to "{ useUnifiedTopology: False }"

### ISSUE THREAD

**Issue by SatyamSSJ10** [bhigginsuk/discord-rss-fetcher#26]
I need to make it true, can you tell me where is "const client" of mongo in the bot files so I can add { useUnifiedTopology: true }

**Comment by bhigginsuk** [comment]
In my shared library: https://github.com/bhigginsuk/disharmony/blob/master/src/database/mongo-client.ts#L63
Loaded as an npm dependency: https://github.com/bhigginsuk/discord-rss-fetcher/blob/master/package.json#L12

**Comment by SatyamSSJ10** [comment]
Thanks, I corrected it but I think you should explain it more in case someone who doesn't know much about it comes with this problem
