### ISSUE TITLE
Bot stops fetching RSS, Monitor JS is also not working

### ISSUE THREAD

**Issue by SatyamSSJ10** [bhigginsuk/discord-rss-fetcher#27]
Bot stops fetching RSS out of the blue, the restart method is not working

**Comment by bhigginsuk** [comment]
There's a few potential different causes for this. The RSS feed might not be updating as frequently as you expect, or the server may have blocked you for too many requests. It could also be a problem with the bot, but I don't have the time or interest to work on these projects anymore to take a look.

The best thing to do is to look in the logs and see whether there's any relevant or useful messages there.

As always the code is entirely open source so you're welcome to work on the project yourself, let me know if you have any specific questions.
